/**
 * Labels i18n des illustrations du blog (les `data-i18n` des SVG themed de
 * « Six mois d'IA en local »). Le composant Illustration inline le SVG et
 * remplace chaque nœud `<text data-i18n="key">` par le label de la locale.
 *
 * Les valeurs sont prêtes pour un nœud de texte SVG : `>` est échappé en `&gt;`,
 * `&` en `&amp;`. Les apostrophes restent littérales (valides en XML).
 */
type Labels = Record<string, string>;

export const ILLUSTRATION_LABELS: Record<'fr' | 'en', Labels> = {
  fr: {
    'nav.context': 'contexte',
    'nav.docs': 'doc indexée',
    'nav.skills': 'skills',
    'nav.agents': 'agents',
    'nav.guards': 'garde-fous',
    'ctx.level.global': 'global',
    'ctx.level.ios': 'iOS',
    'ctx.level.project': 'projet',
    'ctx.level.dev': 'dev',
    'ctx.rule.ddd': '› domaine pur, zéro dépendance infra',
    'ctx.rule.i18n': '› strings via catalogue, jamais en dur',
    'ctx.rule.migrations': '› ALTER TABLE oui, DROP TABLE non',
    'ctx.rule.tests': '› @Test décrit en FR, nommé en EN',
    'doc.query': '&gt;_ tailwind ?',
    'doc.stale': 'mémoire du modèle · périmée',
    'doc.fresh': 'Qdrant — ma doc (via MCP)',
    'doc.fresh.note': "consultée d'office avant de répondre",
    'skills.format': 'format',
    'skills.format.sub': 'auto-fix',
    'skills.audits': 'audits',
    'skills.audits.sub': 'parallèle',
    'skills.build': 'build',
    'skills.build.sub': '+ tests',
    'skills.gate': 'PR si tout passe',
    'agents.weather': 'météo',
    'agents.satellite.l1': 'satel-',
    'agents.satellite.l2': 'lite',
    'agents.bera': 'BERA',
    'agents.outings': 'sorties',
    'agents.data.l1': 'données',
    'agents.data.l2': 'réelles',
    'agents.report': 'rapport',
    'guards.commit': 'commit signé IA',
    'guards.push': 'push sur main',
  },
  en: {
    'nav.context': 'context',
    'nav.docs': 'indexed docs',
    'nav.skills': 'skills',
    'nav.agents': 'agents',
    'nav.guards': 'guardrails',
    'ctx.level.global': 'global',
    'ctx.level.ios': 'iOS',
    'ctx.level.project': 'project',
    'ctx.level.dev': 'dev',
    'ctx.rule.ddd': '› pure domain, zero infra dependency',
    'ctx.rule.i18n': '› strings via catalog, never inline',
    'ctx.rule.migrations': '› ALTER TABLE yes, DROP TABLE no',
    'ctx.rule.tests': '› @Test described in FR, named in EN',
    'doc.query': '&gt;_ tailwind ?',
    'doc.stale': "model's memory · outdated",
    'doc.fresh': 'Qdrant — my docs (via MCP)',
    'doc.fresh.note': 'consulted upfront before answering',
    'skills.format': 'format',
    'skills.format.sub': 'auto-fix',
    'skills.audits': 'audits',
    'skills.audits.sub': 'parallel',
    'skills.build': 'build',
    'skills.build.sub': '+ tests',
    'skills.gate': 'PR if all green',
    'agents.weather': 'weather',
    'agents.satellite.l1': 'satel-',
    'agents.satellite.l2': 'lite',
    'agents.bera': 'BERA',
    'agents.outings': 'outings',
    'agents.data.l1': 'real',
    'agents.data.l2': 'data',
    'agents.report': 'report',
    'guards.commit': 'AI-signed commit',
    'guards.push': 'push to main',
  },
};
